### ISSUE TITLE
Prototype for Zen sign on with RPI accounts

### ISSUE THREAD

**Issue by conoramurphy-zz** [CoderDojo/community-platform#1226]
## Goal
Users sign on using profile service for Coderdojo
## Why
Salesforce integration is easier, simplify architecture, unify and reduce legacy cost of CoderDojo.
## How
Create a prototype to better understand the problem

Detailed internal documentation (which is well beyond the scope of this task)
https://docs.google.com/document/d/1KcJnW5KEm75vinobSw-0J8y88U0_D7yQ4wU_CKJY5Jo/edit

# Tasks

- [x] Identify which Hydra version to target ( 1 or Hydra 0.x) with core-team
- [ ] Discussion with Core-team (owners of Profile)
- [ ] Coderdojo request to Profile
- [ ] Coderdojo setup as Profile client (test/dev)
- [ ] Profile redirection back to Coderdojo
- [ ] Coderdojo oauth response handling
- [ ] Bypass/integration with sign on and CoderDojo existing login flow
- [ ] Strategy for importing CoderDojo Users into Profile
- [ ] Strategy for userinfo and how/if it can be used for Coderdojo.  
- [ ] Review Unions user auth flow. Does it need to change to make things easier? 
- [ ] Decide if a proxy service would simply change points
- [ ] Report findings and decided strategy

**Comment by josephwilk** [comment]
Spike to identify problems, and better understand the problem.

**Comment by josephwilk** [comment]
Unlikely Hydra 1 profile support will be released soon, so best to focus on Hydra 0.x integration.

**Comment by josephwilk** [comment]
* Coderdojo and profile use different password hashing. So all passwords would need to be reset when importing coderdojo users to profile users :(
