### ISSUE TITLE
Navigation Standardisations

### ISSUE THREAD

**Issue by conoramurphy-zz** [CoderDojo/community-platform#1228]
**Business Goal**
Have simplified navigation that only shows what is relevant to the user

**Possible Issues**
- [ ] Remove attend-a-dojo from the navigation
- [ ] Trim the menu for people without any ticketing admin privileges
- [ ] Use the menu now on coderdojo.com homepage as a guide for what we actually care about. Rearrange the top level menu to be under 3/4 headings to simplify navigation.

Related to #225
