### ISSUE TITLE
Eventbrite integration improvements grouping

### ISSUE THREAD

**Issue by conoramurphy-zz** [CoderDojo/community-platform#1229]
This is a ticket a holding for Eventbrite improvements until a decision is made to cull/expand them.

- [ ] Embedded event using EB redirect to Zen booking as well as EB
- [ ] Eventbrite integration isn't clear that only future events will appear (no initial sync)
- [ ] Eventbrite integration doesn't support multiple webhook per account (?)
- [ ] Create a mailing list that cuts anyone who created an event in the last 3 months and hasn't linked in Eventbrite
- [ ] Investigate handling of deletion of events in EB integration
- [ ] Eventbrite multiple eventbrite locations
- [ ] Investigate handling of series in EB integration
- [ ] Investigate and decide how to handle EB eventseries
