### ISSUE TITLE
Simplification and rebuild of "Create Event" form

### ISSUE THREAD

**Issue by conoramurphy-zz** [CoderDojo/community-platform#1230]
**Business Value**
Since 90% of user events are very simple 1 ticket type events. Our create event form should prioritise that, and allow some minor complexity as a secondary option

**To-Do**
- [x] Review wireframes and test
- [x] Research sensible defaults
- [x] Look at recurring events vs term and usage and value
- [ ] Custom question, allow a text entry and a text response. No data types.
- [x] Move any version of sessions under "advanced"
- [x] Decide where you end up when you create the event, Dojo page?

**Blogpost for launch**
https://coderdojo.com/?p=17691 (flag with Nuala)

**Launched**
`2019-08-08 13:39:55.004+00`

**To monitor**
Old vs new events usage.
support.
404 etc?

**Designs**
https://share.goabstract.com/55e46582-889a-4085-bca6-82be52bf1afb

![create](https://user-images.githubusercontent.com/3603234/57370083-2bbf6d00-7187-11e9-8ff9-c8cbd05d6241.png)
![create2](https://user-images.githubusercontent.com/3603234/57370084-2bbf6d00-7187-11e9-9ec4-79d7deacc8d8.png)

**Linked Issues**
- [x] #1189 
- [x] #1061
- [x] #1062
- [x] #1059

**Comment by Wardormeur** [comment]
Question from Slack:
Design for the date: datepicker vs 3 number fields ?
Design for the hours: hourpicker vs 2 number fields ?
What are the default values for the options from the current create event form? (notify on applicant and such)

**Comment by Wardormeur** [comment]
From https://github.com/CoderDojo/community-platform/issues/1259#issue-433321614, can you confirm that "Any unexpected ticket (coming from the old event UI) should be resetted to the 2 default ones" ?

**Comment by conoramurphy-zz** [comment]
> Design for the date: datepicker vs 3 number fields ?

I don't really mind here. Are you saying 3 number fields is better or 3 number fields is easier (both valid)
> Design for the hours: hourpicker vs 2 number fields ? 

Same as above. Which do you rather and why. I just went with common styles used in google calendar.

> From #1259 (comment), can you confirm that "Any unexpected ticket (coming from the old event UI) should be resetted to the 2 default ones" ?

Asked for clarification on that ticket

**Comment by Wardormeur** [comment]
Number fields are annoying for international, because of the ordering. However, date pickers are a generally hated component when it comes to UX.
Same for time, annoying due to PM/AM only being an english thing.
Thoughts @DanielBrierton ?

**Comment by conoramurphy-zz** [comment]
Talked about in Slack. Particularly gregwood confirmed that 

> date pickers (calendar dropdown type things) are dead annoying, inaccessible, hard to use on a phone, etc
three fields for day, month and year are way easier to use. the month should be the names, not numbers
maybe consider separating the Event date label heading into two: Event date and Event time

So I'll take another run at a version of the wireframe tomorrow.

**Comment by Wardormeur** [comment]
Bump on
> What are the default values for the options from the current create event form? (notify on applicant, ticket approval, public event)

**Comment by conoramurphy-zz** [comment]
- Notify on applicant (false)
- ticket approval (false)
- public event (true)

Make sense?

**Comment by Wardormeur** [comment]
We've looked into the librairies, and it seems that https://chronotruck.github.io/vue-ctk-date-time-picker/ is a decent solution if we're going the library way.
My only issue with normal html fields comes down to handling PM/AM for time, and offering an experience which ease the input.
Another alternative is the support of the native datepicker, but the support is not extroardinary (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local)

**Comment by conoramurphy-zz** [comment]
![Screenshot 2019-05-01 at 14 32 04](https://user-images.githubusercontent.com/3603234/57019292-f7dfc700-6c1d-11e9-9175-e09450791154.png)

This is basically what I'm thinking. A seperate date selector (as it's a single date not a range), and a time range selector. Does this work with the above library. Splitting them

**Comment by Wardormeur** [comment]
Natives splitting are documented here : 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date
That might be an issue since native input for date/time don't work on IE. We can validate it, but that'll be an issue presenting the error message.

For vue-ctk-date-time-picker, the example for both scenario are displayed on the exact link I sent on the previous message.
In the end, this doesn't describe the issue I'm facing @conoramurphy : what are we expecting the user to do with those inputs? Are they supposed to
  - Enter> scroll day > tab or click >scroll month > tab or click > scroll year
 or
 - Enter, click day based on a visual calendar
 or
 - Enter>type day>automatic slash added>type month>...
or ..?
Notice that for the native inputs, it's up to the browser how to display it. We have few to no capacity to change it.

**Comment by conoramurphy-zz** [comment]
The lack of Safari support would be more a blocker for native for me.

For the library can you point me to where that does a time range picker by itself? The ones I see are either range, or a time picker and the visual customiser blocks having both those options on at the same time.

Ideally the calendar picker would be 

 > click day based on a visual calendar. 

But I'm not overly opinionated here once it's clean and we're not making them do anything they shouldn't need to.

**Comment by Wardormeur** [comment]
Apologies, I didn't understand you wanted a time-**range** picker. This doesn't exists, not in native, not in this lib either.
It's going to be 2 fields in both scenario.

**Comment by conoramurphy-zz** [comment]
Ok, then I'm happy with trying three different inputs.
A 
[Calendar picker] [Start time picker] to [End time picker]

**Comment by conoramurphy-zz** [comment]
It's observed as working. Waiting until the end of August for monitoring results.

**Comment by conoramurphy-zz** [comment]
**Statistical review**
Overall: event usage is up around 80% on last year, pre form launch it was up 30% oin last year month to month. 72.3% of events created on Zen post launch  are with the new form. However of that 27.7% using the old form around 66% could be using the new form. Leaving 91% of events accounted for functionally with the new form.

The percentage of new clubs using events has gone up nearly 10% (depending on how you calculate it).

**Review of the non-converted**
Out of the last 50 events created using the old form (all of these are in October). 67% do not need any special features. Possible reasons they used the old form are... translation issues, curiosity etc.

**TBD**
- @conor to chase translation. After 2/3 weeks with at least Dutch, German, Spanish done hopefully we push the new form usage past 85%.
