### ISSUE TITLE
Regional Bodies

### ISSUE THREAD

**Issue by conoramurphy-zz** [CoderDojo/community-platform#1231]
**Business Goal/Theory**
By providing simple tools to Regional bodies we greatly increase the utility for Regional Bodies and increase Zen usage.

**Jobs**
- [ ] Regional Bodies need to be able to report on various high-level stats from their communities
- [ ] Regional body joining should be automatic if the rules of being part of the body are easy geographical rules
- [ ] Regional body joining should be manual by the RPI team if any other case needs to be met

**To-Do**
- [ ] Get a regional body that will move everyone over if we fulfil some basic requirements. Use them as a test case to make sure we only build used things.
