### ISSUE TITLE
As a volunteer, I want to easily volunteer at clubs and not be left in limbo.

### ISSUE THREAD

**Issue by conoramurphy-zz** [CoderDojo/community-platform#1244]
### Business Goal
Volunteers can currently request to join any club. But are stuck in limbo if there's no reply

### Task
- [ ] Do analysis https://github.com/CoderDojo/community-platform/issues/1247
- [ ] Add in something on the dashboard for the volunteer to show they have "N number of pending requests"
- [ ] Make the notification go the dojo email AND the main champion.

#### Dashboard task detail
In the top section, there should be a message saying 
"You have N pending requests to join a Dojo. Feel free to request to join more Dojos in your area."
The buttons below should stay the same as are currently there until they've actually booked into an event.

**Comment by Wardormeur** [comment]
The current action is a one-click.
What's the expectation here in that email to be written?
Why would we need to record a copy ?
Edit: outdated

**Comment by Wardormeur** [comment]
This has been covered by https://github.com/CoderDojo/cp-zen-platform/commit/5bed7dcaa25a791569296c2dc8e4d0d333186642 and https://github.com/CoderDojo/cp-zen-frontend/commit/3dfc15cd3379184c39fe396bc25152229f1b7e3e
