### ISSUE TITLE
Deployment - rough task list

### ISSUE THREAD

**Issue by dberesford** [CoderDojo/community-platform#166]
- [x] adult forums production: adult forums needs to be moved into the coderdojo vpc
- [x] youth forums production: manual port locked only thing left
- [x] badge server: fully done
- [x] zen: infrastructure & deployment work fully in place
- [x] zen: postgres rds database work all complete
- [x] zen: nginx configuration, how the routing for forums will work, etc
- [ ] certs: elb certs 
- [x] deployment pipeline: fully in place
