### ISSUE TITLE
Translation Errors

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/community-platform#934]
This issue unites all translation errors on Zen. 

## Change the wording
These points are either split up and should be joined or are misspelled.
To mark them as fixed, remove the mistake and set the context in [crowdin](https://crowdin.com/translate/zen-community-platform).

- [ ] ["is public"](https://crowdin.com/translate/zen-community-platform/1/en-ga#336)
- [ ] ["has been successfully approved"](https://crowdin.com/translate/zen-community-platform/1/en-ga#502)
- [ ] ["has been received"](https://crowdin.com/translate/zen-community-platform/1/en-ga#2671)
- [ ] ["To"](https://crowdin.com/translate/zen-community-platform/1/en-ga#338) - context missing/incorrect when used several times in other contexts and different languages
- [ ] ["CityTown"](https://crowdin.com/translate/zen-community-platform/1/en-de#q=Citytown)
- [ ] ["I have read and accept the"](https://crowdin.com/translate/zen-community-platform/1/en-de#197) - these are multiple strings but it should be one.
- [ ] ["contribute code"](https://crowdin.com/translate/zen-community-platform/1/en-de#3361) [context: footer](https://zen.coderdojo.com/) - is split into multiple parts, should be one string with links
- [ ] ["Open, come along"](https://crowdin.com/translate/zen-community-platform/1/en-de#3820) [context](https://zen.coderdojo.com/dojo/861)
- [ ] ["Reset stale."](https://crowdin.com/translate/zen-community-platform/1/en-nl#430) - could be worded better
- [ ] "Terms and Conditions here" [context](https://zen.coderdojo.com/register) - should be put into the sentence with the links ![](https://cloud.githubusercontent.com/assets/11661560/12645877/34985b76-c5cd-11e5-9333-d0c3e0794333.png)
- [ ] ["error.general"](https://crowdin.com/translate/zen-community-platform/1/en-sl#449) [messages.po](https://github.com/CoderDojo/cp-zen-platform/blob/d9dc98254d3f1593fb69306c9800bc2a2daf1b2a/web/locale/en_US/messages.po#L1720) should be formulated properly for consistency #933

## Translation forgotten

- [ ] ["Full Name"](https://crowdin.com/translate/zen-community-platform/1/en-de#q=Full+name) [context](https://zen.coderdojo.com/register)
- [ ] ["Parent/Guardian"](https://crowdin.com/translate/zen-community-platform/1/en-de#q=Parent%2FGuardian) [context](http://zen.coderdojo.com/dojo/861) ![](https://cloud.githubusercontent.com/assets/564768/11827657/325d4918-a38e-11e5-970a-7a92d15db52c.PNG)
-  [context](https://zen.coderdojo.com/register) ![](https://cloud.githubusercontent.com/assets/564768/11827618/e51383ac-a38d-11e5-909a-3235116499a7.PNG)
    - [ ] ["password"](https://crowdin.com/translate/zen-community-platform/1/en-de#q=password)
    - [ ] "email"
- on [manage a dojo site](https://zen.coderdojo.com/dashboard/my-dojos/0be123e7-c9be-4002-a3cf-f0c8550f749a/events) ![capture](https://cloud.githubusercontent.com/assets/564768/13698859/11878f6e-e777-11e5-9e88-f94abef2a08e.PNG)
    - [ ] "published"
    - [ ] "Manage Dojo Events"
    - [ ] "December 20th 2015"
- on [manage event site](https://zen.coderdojo.com/dashboard/dojo/0be123e7-c9be-4002-a3cf-f0c8550f749a/event-form/cdebe884-caa8-46f7-9e1f-d7581049a855)
    - [ ] "one-off" - type ![](https://cloud.githubusercontent.com/assets/564768/11919875/313149d0-a75e-11e5-8e4f-dd8271d32193.PNG)
    - [ ] "published" ![](https://cloud.githubusercontent.com/assets/564768/11919876/3136bf82-a75e-11e5-9533-ac0557a29781.PNG)
    - [ ] the date ![](https://cloud.githubusercontent.com/assets/564768/11919877/3136c19e-a75e-11e5-8a88-e54e658c4d4a.PNG)
- [ ] titles [context](ttps://zen.coderdojo.com/dashboard/start-dojo) #928 ![](https://cloud.githubusercontent.com/assets/564768/13570174/eac8ed9e-e46c-11e5-95ea-8af70321475a.PNG)
- [ ] "dojo.setup.confirmation" #927 - When I register myself as a Dojo Champion, I get a confirmation that says "dojo.setup.confirmation". That should be some useful text. ![](https://cloud.githubusercontent.com/assets/564768/13570075/5acebd7c-e46c-11e5-9765-e9be0a655827.PNG)
- [starting a dojo](https://zen.coderdojo.com/dashboard/start-dojo) #929
    - ![untitled](https://cloud.githubusercontent.com/assets/564768/13570211/38b90818-e46d-11e5-974b-305f6c6f2b6a.png)
        - [ ] Tao translation 
        - [ ] The background is checked
    - ![capture](https://cloud.githubusercontent.com/assets/564768/13570314/0fdd88b4-e46e-11e5-907d-e4e60420d8a6.PNG)
        - [ ] "Embody the ethos" translation and the `*` is not resolved
        - [ ] "Please read ECHO" translation
    - [ ] Contributions to the movement list is not in crowdin
        ![capture](https://cloud.githubusercontent.com/assets/564768/13570568/49d5a91a-e46f-11e5-9a78-20e93dc4f62f.PNG)
    - [ ] location help text occurs on [crowdin](https://crowdin.com/translate/zen-community-platform/1/en-de#q=Cork) but not on website.
    ![capture](https://cloud.githubusercontent.com/assets/564768/13570667/faac69cc-e46f-11e5-895a-dab22ddba273.PNG)
    - ![capture](https://cloud.githubusercontent.com/assets/564768/13570830/03d78080-e471-11e5-9ddb-40f37d545643.PNG)
        - [ ] time example is not fully shown
        - [ ] mistake in English translation string "its" vs. "it's" and no translation.
- [ ] ["Join Request Sent!"](https://crowdin.com/translate/zen-community-platform/1/en-de#2584) [context](https://zen.coderdojo.com/dashboard/dojo/de/berlin/dojo-berlin-friedrichshain-1) #931 - When I click to join a dojo, the confirmation message is not translated. ![](https://cloud.githubusercontent.com/assets/564768/13602038/5e71034a-e534-11e5-8cd2-f7da52b72e90.PNG)
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 

Editing ....

Obsoletes #820

**Comment by adhorrig** [comment]
Thanks @niccokunzmann , maybe we should also introduce a translation label also?

**Comment by niccokunzmann** [comment]
@adhorrig sure. I can not do that...

**Comment by Wardormeur** [comment]
Awesome, thanks @niccokunzmann

**Comment by tangentfairy** [comment]
That is so useful and clearer, thank you Nicco!

**Comment by Wardormeur** [comment]
Hey @niccokunzmann , do you have an automated way to check what's translated/n ?

**Comment by Wardormeur** [comment]
#927  deployd & ticked :+1:

**Comment by Wardormeur** [comment]
#917 deployed & ticked :+1:

**Comment by niccokunzmann** [comment]
Translation forgotten: 
- "the CoderDojo Foundation", in the footer of every site. e.g. on the [main page](https://zen.coderdojo.com/). 
![capture](https://cloud.githubusercontent.com/assets/564768/16653742/ae15606c-4452-11e6-993c-b8c2b4c684c2.PNG)

**Comment by rhemon** [comment]
@niccokunzmann i would like to try solving this issue

**Comment by leona-ya** [comment]
Hello @niccokunzmann, i translated the invited to session page(https://crowdin.com/translate/zen-community-platform/1192/en-de). GCI2017

**Comment by Wardormeur** [comment]
I've ticked a bunch of them, most of them are nowadays old pages that have been rewritten.
If you find more on the new pages, we're open :)
